version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - desafio-node-net

  appnode:
    build: 
      context: ./node
    container_name: appnode
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 --timeout 10s docker-entrypoint.sh  
    restart: always
    tty: true
    networks:
      - desafio-node-net

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    tty: true
    restart: always
    depends_on:
      - appnode
    ports:
      - "8080:80"
    networks:
      - desafio-node-net

networks:
  desafio-node-net:
    driver: bridge